#数据库配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    enterprise:  # 企业
      url: jdbc:mysql://139.198.115.132:3306/t_enterprise?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    admin:   # 用户
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://ip:port/t_admin?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
      username: root
      password: xxxxxxxx
    store:  # 商城
      url: jdbc:mysql://139.198.115.132:3306/t_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    config:  # 配置
      url: jdbc:mysql://139.198.115.132:3306/t_config?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    spider:  # 爬虫
      url: jdbc:mysql://139.198.115.132:3306/t_spider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver




