#数据库配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    enterprise:  # 企业
      jdbc-url: jdbc:mysql://139.198.115.132:3306/t_enterprise?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    admin:   # 用户
      jdbc-url: jdbc:mysql://139.198.115.132:3306/t_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    store:  # 商城
      jdbc-url: jdbc:mysql://139.198.115.132:3306/t_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    config:  # 配置
      jdbc-url: jdbc:mysql://139.198.115.132:3306/t_config?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    spider:  # 爬虫
      jdbc-url: jdbc:mysql://139.198.115.132:3306/t_spider?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver
    web:  # 门户
      jdbc-url: jdbc:mysql://139.198.115.132:3306/t_web?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: because
      driver-class-name: com.mysql.cj.jdbc.Driver




