spring:
  cache:
    redis:
      time-to-live: 180000 #设置缓存过期时间
  redis:
    host: 192.168.0.158
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: 1ms # 最大阻塞时间
        max-idle: 4
        min-idle: 0















