spring:
  elasticsearch:
    uris: http://192.168.0.136:9200,http://192.168.0.136:9200,http://192.168.0.136:9200
    username: elastic
    password: Sy_*lqEciee7N-a*NB0p































