spring:
  redis:
    sentinel:
      master: mymaster
      username:
      password:
      dataNode:
        username:
        password:
        database:
      nodes:
        - 192.168.0.158:8004
        - 192.168.0.158:8005
        - 192.168.0.158:8006

    connect-timeout: 1000
