spring:
  cache:
    redis:
      time-to-live: 180000 #设置缓存过期时间
  redis:
    master:
      host: 192.168.1.100
      port: 6379
    slaves:
      - host: 192.168.1.101
        port: 6379
      - host: 192.168.1.102
        port: 6379







