server:
  port: 8080

spring:
  application:
    name: redis-master-slaves
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0

# redis主从机参数配置
redis:
  ms:
    redis-master:
      host: 192.168.0.158
      port: 7001
      password:
    redis-slaves:
      - host: 192.168.0.158
        port: 7002
        password:
      - host: 192.168.0.158
        port: 7003
        password: